src/Entity/Course.php
<?php

namespace App\Entity;

use App\Repository\CourseRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CourseRepository::class)
 */
class Course
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank
     */
    private $CharacterCode;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $CourseName;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $CourseDescription;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCharacterCode(): ?string
    {
        return $this->CharacterCode;
    }

    public function setCharacterCode(string $CharacterCode): self
    {
        $this->CharacterCode = $CharacterCode;

        return $this;
    }

    public function getCourseName(): ?string
    {
        return $this->CourseName;
    }

    public function setCourseName(string $CourseName): self
    {
        $this->CourseName = $CourseName;

        return $this;
    }

    public function getCourseDescription(): ?string
    {
        return $this->CourseDescription;
    }

    public function setCourseDescription(?string $CourseDescription): self
    {
        $this->CourseDescription = $CourseDescription;

        return $this;
    }
}

templates/profile/history.html.twig
{% extends 'base.html.twig' %}

{% block title %}История транзакций{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>История транзакций</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Айди</th>
                <th>Создана в</th>
                <th>Тип транзакции</th>
                <th>Код курса</th>
                <th>Сумма
                    <br>(в рублях)
                </th>
            </tr>
            </thead>
            <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td>{{ transaction.created_at }}</td>
                    <td>
                        {% if(transaction.type == 'deposit') %}
                            Начисление
                        {% endif %}
                        {% if(transaction.type == 'payment') %}
                            Списание
                        {% endif %}
                    </td>
                    {% if transaction.course_code  is defined %}
                        <td>
                            {{ transaction.course_code }}
                            {% for course in courses %}
                                {% if(course.characterCode == transaction.course_code) %}
                                    <br>
                                    <a href="{{ path('app_course_show', {'id': course.id}) }}">{{ course.courseName }}</a>
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td>{{ transaction.amount }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Профиль{% endblock %}

{% block body %}
    <div class="container-fluid">
        <h1>Профиль</h1>

        <div>
            <p>Имейл: {{ app.user.email }}</p>
            <p>
                Роль: {% if is_granted('ROLE_SUPER_ADMIN') %}
                    Администратор
                {% else %}
                    Пользователь
                {% endif %}
            </p>
            <p>
                Баланс: {{ balance }}
            </p>
            <a href="{{ path('app_profile_history') }}">История транзакций</a>
        </div>
    </div>
{% endblock %}